.PHONY: init test install

install:
	chmod +x install_airflow.sh && ./install_airflow.sh

start:
	chmod +x start_airflow.sh && ./start_airflow.sh

stop:
	chmod +x stop_airflow.sh && ./stop_airflow.sh
